"""empty message

Revision ID: 68297871baa5
Revises: 
Create Date: 2019-07-17 21:24:07.787847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68297871baa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_kind_name'), 'event_kind', ['name'], unique=True)
    op.create_table('function',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_name'), 'function', ['name'], unique=True)
    op.create_index(op.f('ix_function_salary'), 'function', ['salary'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('start_doc_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_start_doc_type_name'), 'start_doc_type', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('workplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workplace_name'), 'workplace', ['name'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('contract_begin', sa.DateTime(), nullable=True),
    sa.Column('work_end', sa.DateTime(), nullable=True),
    sa.Column('contract_end', sa.DateTime(), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.Column('workplace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['function.id'], ),
    sa.ForeignKeyConstraint(['workplace_id'], ['workplace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_contract_begin'), 'worker', ['contract_begin'], unique=False)
    op.create_index(op.f('ix_worker_contract_end'), 'worker', ['contract_end'], unique=False)
    op.create_index(op.f('ix_worker_name'), 'worker', ['name'], unique=True)
    op.create_index(op.f('ix_worker_work_end'), 'worker', ['work_end'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('event_kind_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('sent_to_hr', sa.Boolean(), nullable=True),
    sa.Column('sent_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['event_kind_id'], ['event_kind.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_begin'), 'event', ['begin'], unique=False)
    op.create_index(op.f('ix_event_sent_date'), 'event', ['sent_date'], unique=False)
    op.create_table('start_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('sent_to_hr', sa.Boolean(), nullable=True),
    sa.Column('sent_date', sa.Date(), nullable=True),
    sa.Column('start_doc_type', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['start_doc_type'], ['start_doc_type.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_start_docs_sent_date'), 'start_docs', ['sent_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_start_docs_sent_date'), table_name='start_docs')
    op.drop_table('start_docs')
    op.drop_index(op.f('ix_event_sent_date'), table_name='event')
    op.drop_index(op.f('ix_event_begin'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_worker_work_end'), table_name='worker')
    op.drop_index(op.f('ix_worker_name'), table_name='worker')
    op.drop_index(op.f('ix_worker_contract_end'), table_name='worker')
    op.drop_index(op.f('ix_worker_contract_begin'), table_name='worker')
    op.drop_table('worker')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_workplace_name'), table_name='workplace')
    op.drop_table('workplace')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_start_doc_type_name'), table_name='start_doc_type')
    op.drop_table('start_doc_type')
    op.drop_table('role')
    op.drop_index(op.f('ix_function_salary'), table_name='function')
    op.drop_index(op.f('ix_function_name'), table_name='function')
    op.drop_table('function')
    op.drop_index(op.f('ix_event_kind_name'), table_name='event_kind')
    op.drop_table('event_kind')
    # ### end Alembic commands ###
